import { InjectionRecord } from './storage';
import { getBodyLabel } from './i18n';
import type { Language } from './storage';

/**
 * Export records to CSV format
 */
export function exportToCSV(records: InjectionRecord[], language: Language): void {
  if (records.length === 0) {
    alert(language === 'ja' ? 'エクスポートする記録がありません' : 'No records to export');
    return;
  }

  // CSV header
  const headers = language === 'ja'
    ? ['日付', '時刻', '部位', '痛みレベル', 'メモ']
    : ['Date', 'Time', 'Body Part', 'Pain Level', 'Notes'];

  // Convert records to CSV rows
  const rows = records.map((record) => {
    const bodyPart = getBodyLabel(language, record.side, record.area);
    const date = record.date;
    const time = new Date(record.timestamp).toLocaleTimeString(
      language === 'ja' ? 'ja-JP' : 'en-US',
      { hour: '2-digit', minute: '2-digit' }
    );
    const painLevel = record.painLevel ? record.painLevel.toString() : '';
    const notes = record.notes ? `"${record.notes.replace(/"/g, '""')}"` : '';

    return [date, time, bodyPart, painLevel, notes].join(',');
  });

  // Combine header and rows
  const csv = [headers.join(','), ...rows].join('\n');

  // Create blob and download
  const blob = new Blob(['\uFEFF' + csv], { type: 'text/csv;charset=utf-8;' });
  const link = document.createElement('a');
  const url = URL.createObjectURL(blob);
  
  link.setAttribute('href', url);
  link.setAttribute('download', `uttar_records_${new Date().toISOString().split('T')[0]}.csv`);
  link.style.visibility = 'hidden';
  
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
}

/**
 * Export records to PDF format
 */
export function exportToPDF(records: InjectionRecord[], language: Language): void {
  if (records.length === 0) {
    alert(language === 'ja' ? 'エクスポートする記録がありません' : 'No records to export');
    return;
  }

  // Create HTML content for PDF
  const title = language === 'ja' ? 'Uttar 注射記録' : 'Uttar Injection Records';
  const dateLabel = language === 'ja' ? '日付' : 'Date';
  const timeLabel = language === 'ja' ? '時刻' : 'Time';
  const bodyPartLabel = language === 'ja' ? '部位' : 'Body Part';
  const painLevelLabel = language === 'ja' ? '痛みレベル' : 'Pain Level';
  const notesLabel = language === 'ja' ? 'メモ' : 'Notes';

  const tableRows = records
    .map((record) => {
      const bodyPart = getBodyLabel(language, record.side, record.area);
      const date = record.date;
      const time = new Date(record.timestamp).toLocaleTimeString(
        language === 'ja' ? 'ja-JP' : 'en-US',
        { hour: '2-digit', minute: '2-digit' }
      );
      const painLevel = record.painLevel ? record.painLevel.toString() : '-';
      const notes = record.notes || '-';

      return `
        <tr>
          <td>${date}</td>
          <td>${time}</td>
          <td>${bodyPart}</td>
          <td>${painLevel}</td>
          <td>${notes}</td>
        </tr>
      `;
    })
    .join('');

  const htmlContent = `
    <!DOCTYPE html>
    <html>
    <head>
      <meta charset="utf-8">
      <title>${title}</title>
      <style>
        body {
          font-family: Arial, sans-serif;
          margin: 40px;
          color: #333;
        }
        h1 {
          color: #D4A574;
          border-bottom: 2px solid #D4A574;
          padding-bottom: 10px;
        }
        .meta {
          margin: 20px 0;
          color: #666;
        }
        table {
          width: 100%;
          border-collapse: collapse;
          margin-top: 20px;
        }
        th {
          background-color: #D4A574;
          color: white;
          padding: 12px;
          text-align: left;
          font-weight: bold;
        }
        td {
          padding: 10px;
          border-bottom: 1px solid #ddd;
        }
        tr:hover {
          background-color: #f5f5f5;
        }
        .footer {
          margin-top: 40px;
          text-align: center;
          color: #999;
          font-size: 12px;
        }
      </style>
    </head>
    <body>
      <h1>${title}</h1>
      <div class="meta">
        <p>${language === 'ja' ? 'エクスポート日時' : 'Exported on'}: ${new Date().toLocaleString(language === 'ja' ? 'ja-JP' : 'en-US')}</p>
        <p>${language === 'ja' ? '総記録数' : 'Total records'}: ${records.length}</p>
      </div>
      <table>
        <thead>
          <tr>
            <th>${dateLabel}</th>
            <th>${timeLabel}</th>
            <th>${bodyPartLabel}</th>
            <th>${painLevelLabel}</th>
            <th>${notesLabel}</th>
          </tr>
        </thead>
        <tbody>
          ${tableRows}
        </tbody>
      </table>
      <div class="footer">
        <p>Generated by Uttar - Self-injection record tracking app</p>
      </div>
    </body>
    </html>
  `;

  // Open print dialog
  const printWindow = window.open('', '_blank');
  if (printWindow) {
    printWindow.document.write(htmlContent);
    printWindow.document.close();
    printWindow.focus();
    
    // Wait for content to load, then print
    setTimeout(() => {
      printWindow.print();
    }, 250);
  } else {
    alert(language === 'ja' ? 'ポップアップがブロックされました。ブラウザの設定を確認してください。' : 'Popup blocked. Please check your browser settings.');
  }
}
